import React from "react";

export const styles: Record<string, React.CSSProperties> = {
    app: {
        minHeight: '100vh',
        minWidth: '100vw',
        display: 'flex',
        flexDirection: 'column',
        background: '#071023',
        color: '#e6eef8',
        fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue'",
    },
    nav: {
        zIndex: 20,
        position: 'sticky',
        top: 0,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 16px',
        backdropFilter: 'blur(6px)',
        background: 'rgba(255,255,255,0.03)',
        borderBottom: '1px solid rgba(255,255,255,0.03)',
        flexWrap: 'wrap',
        gap: 12,
    },
    brand: { fontWeight: 700, letterSpacing: 0.6, fontSize: '1.1rem' },
    links: {
        display: 'flex',
        gap: 10,
        flexWrap: 'wrap',
    },
    navBtn: {
        background: 'transparent',
        color: 'inherit',
        border: 'none',
        padding: '6px 10px',
        cursor: 'pointer',
        borderRadius: 0,
        fontSize: '0.95rem',
        whiteSpace: 'nowrap',
        transition: "all 0.3s ease",
    },
    navBtnActive: {
        padding: "0.5rem 1rem",
        border: "1px solid white",
        background: "white",
        color: "black",
        borderRadius: "0px",
        cursor: "pointer",
        transition: "all 0.3s ease",
    },
    main: {
        zIndex: 10,
        flex: 1,
        // padding: '16px',
        width: '100%',
        boxSizing: 'border-box',
    },
    footer: {
        zIndex: 10,
        position: 'sticky',
        bottom: 0,
        padding: '12px 8px',
        textAlign: 'center',
        color: 'rgba(230,238,248,0.6)',
        fontSize: '0.85rem',
    },
    heroWrap: {
        position: 'absolute',
        // left: 0,
        // position: 'relative',
        zIndex: 1,
        top: 0,
        height: '100vh',
        // minHeight: 380,
        borderRadius: 12,
        // overflow: 'hidden',
        boxShadow: '0 10px 30px rgba(2,6,23,0.6)'
    },
    canvasContainer: {
        position: 'absolute',
        inset: 0
    },
    heroContent: {
        position: 'absolute',
        left: 228,
        top: '18%',
        zIndex: 2,
        maxWidth: '80%',
        paddingRight: 12,
    },
    workContent: {
        position: 'absolute',
        left: 228,
        top: '15%',
        zIndex: 2,
        minWidth: '80%',
        paddingRight: 12,
    },
    cta: {
        padding: '10px 14px',
        borderRadius: 10,
        border: 'none',
        cursor: 'pointer',
        background: 'linear-gradient(90deg,#6ea8fe,#8b5cf6)',
        color: 'white',
        fontWeight: 600,
        fontSize: '0.9rem',
    },
    page: {
        zIndex: 2,
        maxWidth: 860,
        margin: '20px auto',
        lineHeight: 1.6,
        padding: '0 12px',
        width: '100%',
        boxSizing: 'border-box',

        animation: "fadeSlide 0.6s ease forwards",
        opacity: 0,
        transform: "translateY(20px)",
    },
    container: {
        position: 'absolute',
        minHeight: '60vh',
        width: "220px",
        padding: "1rem",
        display: "flex",
        flexDirection: "column",
        gap: "0.5rem",
        borderRight: "1px solid rgba(255,255,255,0.1)",
    },
    button: {
        padding: "0.75rem",
        border: "none",
        cursor: "pointer",
        color: "#e6eef8",
        borderRadius: "6px",
        fontSize: "0.95rem",
        maxWidth: "200px",
        position: "absolute",
        right: 0,
        backgroundColor: "rgba(0,0,0,0.02)",
    },
    aboutContainer: {
        marginLeft: "280px",
        flex: 1,
        padding: "1.5rem",
        display: "flex",
        flexDirection: "column",
        gap: "1rem",
        position: "relative",
    },
    title: {
        margin: 0,
        fontSize: "1.8rem",
        fontWeight: 600,
    },
    description: {
        maxWidth: "700px",
        lineHeight: 1.6,
        opacity: 0.9,
    },
    subtitle: {
        fontSize: "1.25rem",
        fontWeight: 600,
        marginBottom: "0.5rem",
    },
    list: {
        paddingLeft: "1rem",
    },
    listItem: {
        marginBottom: "0.3rem",
        opacity: 0.9,
    },

};
